name: kulthx-unified-bot
services:
  - name: web
    image: koyeb/nodejs-builder
    build:
      build_context: .
      dockerfile: Dockerfile.koyeb
    ports:
      - port: 8000
        protocol: http
    routes:
      - path: /
        port: 8000
    envs:
      - key: PORT
        value: 8000


