version: '3.8'

services:
  kulthx-bot:
    build: .
    container_name: kulthx-discord-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_PREFIX=${BOT_PREFIX:-!}
      - MAX_SCRIPT_LENGTH=${MAX_SCRIPT_LENGTH:-50000}
      - MAX_SCRIPTS_PER_USER=${MAX_SCRIPTS_PER_USER:-50}
      - PORT=3000
    volumes:
      - ./scripts.json:/app/scripts.json
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  scripts_data:
  logs_data:

